#!/usr/bin/env ansible-playbook

- name: show return value of command module
  hosts: server1
  tasks:
    - name: capture output of id command
      command: id -un
      register: login
    - debug: var=login

- name: show return value of command module as message
  hosts: server1
  tasks:
    - name: capture output of id command
      command: id -un
      register: login
    - debug: msg="Logged in as user {{ login.stdout }} and linux distribution is {{ ansible_distribution }}"
